x-huginn: &huginn
  build: .
  env_file: env
  depends_on:
    - db

services:
  # TODO: reverse proxy to host service
  web:
    <<: *huginn
    ports:
      - 3000:3000
    command: bash -c "bundle exec rails db:migrate &&
      bundle exec rails db:seed &&
      bundle exec rails server -p 3000 -b 0.0.0.0"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  woker:
    <<: *huginn
    network_mode: "host"
    command: bundle exec rails runner bin/threaded.rb
    environment:
      - DATABASE_HOST=0.0.0.0
      - DATABASE_PORT=5431


  db:
    image: postgres:16.1
    ports:
      - 5431:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=huginn
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
