x-huginn: &huginn
  build: .
  env_file: env
  environment:
    - DATABASE_HOST=db
    - DATABASE_PORT=5432
    - SELENIUM_HOST=selenium.firefox
    - SELENIUM_PORT=4444
    - DRIVER=firefox_remote

  depends_on:
    - db

services:
  # TODO: reverse proxy to host service
  web:
    <<: *huginn
    ports:
      - 3000:3000
    command: bash -c "bundle exec rails db:migrate &&
      bundle exec rails db:seed &&
      bundle exec rails server -p 3000 -b 0.0.0.0"
    volumes:
      - ./bin:/opt/bin

  woker:
    <<: *huginn
    command: bundle exec rails runner bin/threaded.rb
    deploy:
      replicas: 2



  db:
    image: postgres:16.1
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=huginn
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  selenium.firefox:
    image: selenium/standalone-firefox:4.16.1
